language: node_js
node_js:
  - "10"
install:
  - npm ci
  - cd functions
  - npm ci
  - cd ..
script:
  - npm run lint
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
before_deploy: npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: npx -p firebase-tools firebase deploy
  on:
    branch: master
