language: node_js
node_js:
  - "10"
install:
  - npm ci
  - cd functions
  - npm ci
  - cd ..
  - sudo apt-get install ffmpeg
script:
  - npm run lint
  - npm run test:build
  - npm run test:snapshot
cache: npm
before_deploy: npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: npx -p firebase-tools firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: master
    condition: "! $TRAVIS_COMMIT_MESSAGE =~ Bump\\ .*\\ from\\ .*\\ to\\ .*"
